### PR TITLE
Initial boilerplate structure

### PR DESCRIPTION
**Pull request by caseywreed**
## Status
**IN DEVELOPMENT**

## Migrations
NO

## Description
Added and edited initial boilerplate files

## Resolves Issue Number
number [link]()

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```

1.

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

### CODE REVIEW

**Comment by jaclkeen** [comment]
LGTM

**Comment by jhoni4** [comment]
LGBT

**Comment by megducharme** [comment]
LGTM

**Comment by interlink3d** [comment]
LGTM

**Comment by dtinsley333** [comment]
LGTM

**Comment by tshavor** [comment]
LGTM

**Comment by jhoni4** [comment]
LGTM

**Pull request merged**
