### PR TITLE
Ts paymentcontroller

### PR DESCRIPTION
**Pull request by tshavor**
## Status
READY

## Migrations
NO

## Description
The Payment controller and AddPayment Views were created.  From the path (http://localhost:5000/Payment/AddPayment), the AddPayment view allows for addition of new payment information.  Once data is added by the user, these data are updated to the database.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Resolves Issue Number
number [#35, #47 ]()

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

The path to this page is:
http://localhost:5000/Payment/AddPayment

Things to enter to add things to the database:

ID: 12345678
CVV: 123
Expiration: 01/01

## Impacted Areas in Application
List general components of the application that this PR will affect:

*Add Payment type and associated views

### CODE REVIEW

**Comment by interlink3d** [comment]
able to add payment type to the DB. Suggested passing a userId through the ASP redirect method.

**Comment by jaclkeen** [comment]
Also able to add payment type to DB. LGTM

**Comment by tshavor** [comment]
Labels and redirects have been added to this branch, and my tests indicate that this work is complete.

**Comment by caseywreed** [comment]
This looks great! Tried a few different variations and all worked out well. The only fix I can foresee Steve bringing up is changing the Expiration Date field to be two dropdown menus-- but the can be taken care of later. Great job!

**Pull request merged**
